#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gridChallenge' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING_ARRAY grid as parameter.
#

def gridChallenge(grid):
    # Write your code here
    
    for i in range(0, len(grid)):
    
        grid[i]=sorted(grid[i])

    
    for i in range(0, len(grid[0][:])):
        for k in range(0, len(grid)-1):
            #print(grid[k - 1][i], grid[k][i])
            if grid[k][i] > grid[k+1][i]:
                return "NO"
   

    return "YES"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        grid = []

        for _ in range(n):
            grid_item = input()
            grid.append(grid_item)

        result = gridChallenge(grid)

        fptr.write(result + '\n')

    fptr.close()
