#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'beautifulPairs' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY A
#  2. INTEGER_ARRAY B
#

def beautifulPairs(A, B):
    # Write your code here
    A=sorted(A)
    B=sorted(B)
    
    
    disjoint_sets=[]
    
    
    for i in range(0,len(A)):
        for j in range(0,len(B)):
            if A[i]==B[j]:
                disjoint_sets.append([i,j])
                del B[j]
                break
     
    if(len(disjoint_sets)==len(A)):
        return len(A)-1
    else:
        return(len(disjoint_sets)+1)
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    A = list(map(int, input().rstrip().split()))

    B = list(map(int, input().rstrip().split()))

    result = beautifulPairs(A, B)

    fptr.write(str(result) + '\n')

    fptr.close()
