#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'largestPermutation' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY arr
#

def largestPermutation(k, arr):
    # Write your code here
    
    if k >= len(arr):
        return sorted(arr, reverse=True)

    
    indeces = {}
    for i in range(0, len(arr)):
        indeces[arr[i]] = i
        
    i=0
    max_element=len(arr)
    

    while k>0 and max_element>1:
        max_element_index = indeces[max_element]
        if max_element != arr[i]:  
            arr[i], arr[max_element_index] = arr[max_element_index], arr[i]
            indeces[arr[i]], indeces[arr[max_element_index]] = i, indeces[arr[i]]
            k-=1
        max_element-=1
        i+=1
        
    

    return arr

            
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = largestPermutation(k, arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
