#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'toys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY w as parameter.
#

def toys(w):
    # Write your code here
    w=sorted(w)
    
    
    smallest_weight_in_container=w[0]
    containers=[]
    container_unit=[]
    
    for each in w:
        if each<=(smallest_weight_in_container+4):
            container_unit.append(each)
        else:
            containers.append(container_unit)
            container_unit=[]
            smallest_weight_in_container=each
            container_unit.append(each)
    
    
    
    
    containers.append(container_unit)        
    print(containers)
            
    return(len(containers))
            
            
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    w = list(map(int, input().rstrip().split()))

    result = toys(w)

    fptr.write(str(result) + '\n')

    fptr.close()
