#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'jimOrders' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts 2D_INTEGER_ARRAY orders as parameter.
#

def jimOrders(orders):
    # Write your code here
    
    
    def take(elem):
        return elem[1]
    
    
    serve_time=[]
    for i in range(1,len(orders)+1):
        serve_time.append([i,orders[i-1][0]+orders[i-1][1]])
        
    serve_time=sorted(serve_time,key=take)
    

    server=[]
    for each in serve_time:
        server.append(each[0])
              
    return server
        
        
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    orders = []

    for _ in range(n):
        orders.append(list(map(int, input().rstrip().split())))

    result = jimOrders(orders)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
