#!/bin/python3


"""https://www.hackerrank.com/challenges/pylons/problem"""

import math
import os
import random
import re
import sys

#
# Complete the 'pylons' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY arr
#

def pylons(k, arr):
    # Write your code here
    
    i=0
    count=0
    last_power_plant=-1
    
    
    
    
    while(i<len(arr)):
        
        i+=k-1
        if i>=len(arr):
            i=len(arr)-1
            print(i)
        while (i>last_power_plant):
            if arr[i]==1:
                count+=1
                last_power_plant=i
                break
            else:
                i-=1
                if (i==last_power_plant):
                    return -1
                
        i+=k
        
    return count
        
        
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = pylons(k, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
