#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'boardCutting' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY cost_y
#  2. INTEGER_ARRAY cost_x
#

def boardCutting(cost_y, cost_x):
    # Write your code here
    
    arr_cost = []
    for each in cost_x:
        arr_cost.append((each,'h'))
        
    for each in cost_y:
        arr_cost.append((each,'v'))
        
    arr_cost = sorted(arr_cost, reverse=True)
    
    X = 1
    Y = 1
    cost = 0
    
    for i in range(0,len(arr_cost)):
        if arr_cost[i][1]=='v':
            Y+=1
            cost+= (X*arr_cost[i][0])
        else:
            X+=1
            cost+= (Y*arr_cost[i][0])
            
    return cost%(10**9+7)
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        first_multiple_input = input().rstrip().split()

        m = int(first_multiple_input[0])

        n = int(first_multiple_input[1])

        cost_y = list(map(int, input().rstrip().split()))

        cost_x = list(map(int, input().rstrip().split()))

        result = boardCutting(cost_y, cost_x)

        fptr.write(str(result) + '\n')

    fptr.close()
