#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'fibonacciModified' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER t1
#  2. INTEGER t2
#  3. INTEGER n
#

def fibonacciModified(t1, t2, n,memo={}):
    fibo = [0] * (n+1)
    fibo[0], fibo[1] = t1, t2
    for i in range(1,n):
        fibo[i+1] = fibo[i-1] + (fibo[i] ** 2)
        
    # print(fibo)
    return fibo[n-1]

    # a=t1
    # b=t2
    # count=2
    # c=0
    # while(n!=count):
    #     count+=1
    #     c=a+b**2
    #     a=b
    #     b=c
    # return c

    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    t1 = int(first_multiple_input[0])

    t2 = int(first_multiple_input[1])

    n = int(first_multiple_input[2])

    result = fibonacciModified(t1, t2, n)

    fptr.write(str(result) + '\n')

    fptr.close()
