#!/bin/python3

"""https://www.hackerrank.com/challenges/migratory-birds/problem"""

import math
import os
import random
import re
import sys

#
# Complete the 'migratoryBirds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def migratoryBirds(arr):
    # Write your code here
    count = 0
    max = math.inf
    arrx = list(set(arr))
    
    for i in range(0,len(arrx)):
        if arr.count(arrx[i])>count:
            count = arr.count(arrx[i])
            max = arrx[i]
            
    return max
            
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
