#!/bin/python3

"""https://www.hackerrank.com/challenges/bon-appetit/problem"""

import math
import os
import random
import re
import sys

#
# Complete the 'bonAppetit' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY bill
#  2. INTEGER k
#  3. INTEGER b
#

def bonAppetit(bill, k, b):
    # Write your code here
    
    del bill[k]
    
    actual_bill=sum(bill)//2
    
    if b-actual_bill==0:
        print("Bon Appetit")
    else:
        print(b-actual_bill)

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
